version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud_network

volumes:
  nextcloud_data:
  db_data:

networks:
  nextcloud_network:
    driver: bridge