version: '3'

nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Nginxの設定ファイルをここに配置
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    external: true